### ISSUE TITLE
Tabs flicker on load

### ISSUE THREAD

**Issue by peter-kehl** [jaatroko/link-status-redux#25] opened 2020-06-21 23:28 UTC
Hi Juha,

Thank you for Link Status Redux.

Unfortunately, when I restart Firefox (77.0.1) and I switch to any tab for the first time in the new FF session, the page loads partially up. Then it flickers/blinks before showing up fully.

Loading of tabs works correctly without Link Status Redux (with all other extensions/settings the same). So the problem is caused by Link Status Redux.

**Comment by jaatroko** [comment] 2020-06-27 16:15
Did you try with a clean profile and LSR the only extension installed? It may not be just LSR, but an interaction with another extension (in which case it is effectively unfixable).

In any case, I have the following observations:

1. I cannot reproduce this (FF 77.0.1, Ubuntu 18.04). Clean profile with LSR, restore previous session on startup set: open couple of test sites (with pages many screens high) in tabs, quit Firefox, start Firefox, switch to a tab and let it load. I do not see any difference in tab loading or rendering between having LSR enabled and not. Do you have an extra problematic site I can test?

2. If the issue is only cosmetic and transient during initial page load, then while such an annoyance can be called a bug, it is not a critical (or even a severe) bug.

3. The way Firefox loads and renders a page is (probably) very opaque to extensions. I do not know FF internals, so giving a definite statement is impossible, but there may not be anything that _can_ be done about this problem.

Considering the above, I will close this issue unless you can provide a way for me to to reproduce it.

**Closed** 2020-07-02 15:36 UTC
