### ISSUE TITLE
Interference with userContent.css

### ISSUE THREAD

**Issue by scarlion1** [jaatroko/link-status-redux#46] opened 2024-01-15 06:57 UTC
I've been trying to reduce strain on my eyes for plugins' config pages (`moz-extension://` URI's), and so I put the following in `userContent.css`:
```
@-moz-document url-prefix("moz-extension:") {
	body {
		background-color: black;
		color: silver;
	}
}
```
This helps a lot.  Problem is all of my websites I visit are now picking up the black `background-color` and overlaying it on all the content, so the entire page is literally blacked out.  The scroll bar is still there and cursor will change if there's a link or text box underneath, but everything is one color.  As soon as I turn off LSR, the page's styling and colors are used and I can see the content again.  I thought I could fix with a `regexp` in the `@-moz-document` rule:
`@-moz-document url-prefix("moz-extension:"), regexp("!(^moz-extension://01295037-866a-401c-9a03-b509e47d3929/.*)") {`
but that doesn't seem to work either.  Guess I should be asking Mozilla for help instead, oh well I already wrote all this.  If you have any ideas or insights, would appreciate knowing!  Thanks

**Comment by scarlion1** [comment] 2024-01-15 09:21
Ok first of all, F regular expressions.  I don't think anyone actually knows how to write one correctly?  Instead it appears requiring hours of trial and error before finally succeeding, or never succeeding.  I just wasted hours of my life trying figure it out, reading others trying to figure it out (mostly for Stylish) and never getting an answer heh... but ChatGPT figured it out in mere seconds.

Input: 

> Can you tell me a regular expression that matches all "moz-extension://" URI's except it excludes "moz-extension://01295037-866a-401c-9a03-b509e47d3929*" ?

Output: 

> Certainly! Here's a regular expression that matches all "moz-extension://" URIs except for "moz-extension://01295037-866a-401c-9a03-b509e47d3929*":
> 
> ```
> ^moz-extension://(?!01295037-866a-401c-9a03-b509e47d3929).*$
> ```
> 
> Explanation:
> - `^` asserts the start of the string.
> - `moz-extension://` matches the literal text "moz-extension://".
> - `(?!01295037-866a-401c-9a03-b509e47d3929)` is a negative lookahead assertion that excludes the specific UUID.
> - `.*` matches any characters (except newline) zero or more times.
> - `$` asserts the end of the string.
> 
> You can use this regular expression in your programming language of choice to match the desired URIs while excluding the specified pattern.

and even explained each piece to me, what a concept.
`@-moz-document regexp("^moz-extension:\\/\\/(?!01295037-866a-401c-9a03-b509e47d3929).*$")` was the final rule that worked and I can have LSR enabled and look at other add-on setting without burning out my eyes and see the rest of the Internet's content.  I'll never waste another minute of my life trying to write a regular expressions again!

**Comment by jaatroko** [comment] 2024-01-15 13:43
Excluding LSR from the CSS match like you have (eventually ;-) done is probably the best way to fix this. I don't know if LSR _can_ do something about this; possibly _something_, but since user CSS takes precedence over page CSS, it may prove to be futile in the end, especially if `!important` is used in the user CSS rule.

Closing issue/question as resolved.

**Closed by jaatroko** 2024-01-15 13:43 UTC

**Comment by scarlion1** [comment] 2025-05-03 04:56
Alright bud, @jaatroko what'd you do!!1
I see in your release notes for 3.21:

> Do not inject the overlink popup into the page until a link is hovered over.

Now, when I hover over a link for the first time after a page is loaded, the entire page area flashes for a split second in whatever background color I have defined in the CSS from my OP.  To recap, this is what I've had in my `userContent.css` for millennia:
```css
/* All Add-On/Extension pages, except Link Status Redux */
@-moz-document regexp("^moz-extension:\\/\\/(?!01295037-866a-401c-9a03-b509e47d3929).*$") {
	body {
		background-color: rgb(0 0 0 / 10%);
		color: silver !important;
	}
	label {
		color: silver;
	}
}
``` 

HOWEVER, during my testing, I found this other selector was the source of this latest issue:
```css
/* All About pages except New Tab */
@-moz-document regexp("^about:(?!newtab(?:$|\\/)).*$") {
	body {
		background-color: rgb(255 0 0 / 100%);
		color: silver;
	}
}
```
I defined different background-color's in my other catch-all selectors, but the quick flash happening when i hover over a link was bright red after making these changes.

Hope you know just what the heck is going here sir!  coz i sure don't.
More importantly, how could my styles be updated to work with these recent changes?
Thanks!

**Comment by jaatroko** [comment] 2025-05-04 13:12
Well, the reason for the flashing was always there, it just was not noticeable when it happened right at the page load (when the window content changes anyway) and with a "normal" background color. I tested with your red about: rule (and only that rule) and I indeed get a red flash on the first link hover. And if I change the code to inject the overlay immediately on page load, I get consistent red flashes when pressing F5 to reload the page.

After some playing around I think I found the root cause. It *seems* that every new window/frame is initially `about:blank` before it sets its actual location URL, and some(most? all?) also get rendered as `about:blank` for that brief time, hence the flash. You can also see this by opening the web developer tools by pressing F12: that window also flashes red when it appears. LSR injects the overlay iframe to the document, and that will also be rendered as `about:blank` before its correct URL takes effect. For security reasons, the code sets `iframe.contentWindow.location` *after* the iframe has been injected (that property does not exist before the iframe has been realised), but it does not help if I set `iframe.src` beforehand, it still flashes red. So there is nothing that can be done from that side.

Your quickest fix is to exclude `about:blank` from your styling. If the about: rule above is the only one that matches `about:blank`, then just replace `newtab` with `(?:newtab|blank)`. There *may* be a way to exclude only those `about:blank` pages that are inside iframes, but I don't know the rules to achieve that.

I am also planning on adding an advanced tweaks & workarounds section to LSR settings, where you can enable and disable various things such as on-demand injection and delayed injection (the latter not implemented yet). This would also help you by reverting to immediate injection, but I am not sure when I will get around to actually implementing this.

**Comment by scarlion1** [comment] 2025-05-11 04:01
> Your quickest fix is to exclude `about:blank` from your styling. If the about: rule above is the only one that matches `about:blank`, then just replace `newtab` with `(?:newtab|blank)`.

Thanks, sir, for the explanation and fix!  This has been working out great:
```css
/* All About pages except New Tab and Blank */
@-moz-document regexp("^about:(?!(?:newtab|blank)(?:$|\\/)).*$") {
  ...
}
```
