### ISSUE TITLE
mark bookmarked links by color (CSS style)

### ISSUE THREAD

**Issue by Enomine88** [jaatroko/link-status-redux#27] opened 2020-09-21 13:10 UTC
Hello Sir,

i use your Firefox-Extension since 2 years and i thank you for your work.

I wondered if i could find an extension which marks visited / bookmarked links in the HTML/CSS style, not by a tooltip.
For visited links this is possible. Example: https://addons.mozilla.org/en-US/firefox/addon/visited-link-enabler/
One other way is to define an own userContent.css in %Firefox-Profiler%/chrome . See http://kb.mozillazine.org/index.php?title=UserContent.css&printable=yes

For example with this css-code you can change the color of visited links for all websites:
`a:visited, a:active {
    color:red!important;
    cursor: pointer !important;
    border: 5px solid green !important;
}`
(border does not work every time but i couldn't figure out why. For example for YouTube the border doesn't work at all and neither does the color.)

Sadly there is no
`a:bookmarked {}`
CSS-style.

Do you think it is possible to alter/overwrite the pages HTML/CSS, to mark visited / bookmarked links by different colors / borders?
For linked images (`<a href...><img></a>`) i would like to have a colored border.

Thanks

Enomine

**Comment by jaatroko** [comment] 2020-09-21 19:34
This is duplicate of issue #24, see that one for the answer. TL;DR: possible: probably; will be in LSR: no.

**Closed by jaatroko** 2020-09-21 19:34 UTC
Labels: duplicate
